name: Integration Tests
'on': pull_request
env:
  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
  REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
  REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
  REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
  REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
  REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
  REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}

  REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
  REACT_APP_RAWG_API_KEY: ${{secrets.REACT_APP_RAWG_API_KEY}}

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Run Integration Tests
        run: yarn test:integration

