name: Testing
'on': pull_request
env:
  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
  REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
  REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
  REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
  REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
  REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
  REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}

  REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
  REACT_APP_RAWG_API_KEY: ${{secrets.REACT_APP_RAWG_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x

      - name: Install dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test:unit

      - name: Run Integration Tests
        run: yarn test:integration

